# Generated by Django 6.0.5 on 2026-06-11 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('refund_transaction', 'Refund Transaction'), ('resolve_transaction', 'Resolve Transaction'), ('suspend_user', 'Suspend User'), ('activate_user', 'Activate User'), ('promote_staff', 'Promote Staff'), ('remove_staff', 'Remove Staff'), ('system', 'System')], max_length=50)),
                ('target_user_email', models.EmailField(blank=True, max_length=254)),
                ('target_reference', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
