# Generated by Django 6.0.5 on 2026-06-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('refund_transaction', 'Refund Transaction'), ('resolve_transaction', 'Resolve Transaction'), ('suspend_user', 'Suspend User'), ('activate_user', 'Activate User'), ('promote_staff', 'Promote Staff'), ('remove_staff', 'Remove Staff'), ('system', 'System'), ('transaction_note_added', 'Transaction Note Added'), ('transaction_status_changed', 'Transaction Status Changed'), ('provider_reference_updated', 'Provider Reference Updated')], max_length=50),
        ),
    ]
