# Generated by Django 6.0.5 on 2026-06-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('refund_transaction', 'Refund Transaction'), ('resolve_transaction', 'Resolve Transaction'), ('suspend_user', 'Suspend User'), ('activate_user', 'Activate User'), ('promote_staff', 'Promote Staff'), ('remove_staff', 'Remove Staff'), ('system', 'System'), ('transaction_note_added', 'Transaction Note Added'), ('transaction_status_changed', 'Transaction Status Changed'), ('provider_reference_updated', 'Provider Reference Updated'), ('ticket_replied', 'Ticket Replied'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_status_changed', 'Ticket Status Changed'), ('ticket_priority_changed', 'Ticket Priority Changed')], max_length=50),
        ),
    ]
