# Generated by Django 6.0.5 on 2026-08-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='meter_type',
            field=models.CharField(blank=True, choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], max_length=20),
        ),
    ]
