"""
Django settings for naijapaypoint project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", default=True, cast=bool)

PAYSTACK_SECRET_KEY = config("PAYSTACK_SECRET_KEY", default="")
PAYSTACK_CALLBACK_URL = config("PAYSTACK_CALLBACK_URL", default="")

VTPASS_BASE_URL = config("VTPASS_BASE_URL", default="")
VTPASS_API_KEY = config("VTPASS_API_KEY", default="")
VTPASS_SECRET_KEY = config("VTPASS_SECRET_KEY", default="")

DOJAH_BASE_URL = os.getenv(
    "DOJAH_BASE_URL",
    "https://sandbox.dojah.io",
)

DOJAH_APP_ID = os.getenv("DOJAH_APP_ID", "")
DOJAH_SECRET_KEY = os.getenv("DOJAH_SECRET_KEY", "")
DOJAH_TIMEOUT = int(os.getenv("DOJAH_TIMEOUT", "30"))

if not DEBUG and (
    not DOJAH_APP_ID or not DOJAH_SECRET_KEY
):
    raise RuntimeError(
        "Dojah production credentials are not configured."
    )

FRONTEND_URL = config(
    "FRONTEND_URL",
    default="http://localhost:3000",
)

EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)

EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default="NaijaPayPoint <no-reply@naijapaypoint.com>",
)

ALLOWED_HOSTS = [
    "naijapaypoint-backend-production.up.railway.app",
    "localhost", 
    "127.0.0.1", 
    "10.0.0.7",  
    ".vercel.app",
]

FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:3000")

AUTH_USER_MODEL = "accounts.User"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'accounts',
    'wallets.apps.WalletsConfig',
    'transactions',
    'payments',
    'airtime',
    'data_services',
    'electricity',
    'cable',
    'notifications',
    'common',
    'beneficiaries',
    'education',
    "referrals.apps.ReferralsConfig",
    "analytics",
    "audit_logs",
    "support",
    "customer_notes",
    "guest_checkout",
    "kyc",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'naijapaypoint.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'naijapaypoint.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(config("DATABASE_URL"))
}

#USE_SQLITE = config("USE_SQLITE", default=False, cast=bool)

#if USE_SQLITE:
#    DATABASES = {
#        "default": {
#            "ENGINE": "django.db.backends.sqlite3",
#            "NAME": BASE_DIR / "db.sqlite3",
#        }
#    }
#else:
#    DATABASES = {
#        "default": dj_database_url.parse(config("DATABASE_URL"))
#    }

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "20/min",
        "user": "100/min",
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8081",
]
