# Generated by Django 6.0.5 on 2026-07-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('cable', 'Cable'), ('education', 'Education'), ('wallet', 'Wallet'), ('payment', 'Payment'), ('kyc', 'KYC'), ('account', 'Account'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
