# Generated by Django 6.0.5 on 2026-07-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ticket_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
    ]
