# Generated by Django 6.0.5 on 2026-07-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('electricity', 'Electricity'), ('cable', 'Cable')], max_length=30)),
                ('provider', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recipient', models.CharField(help_text='Phone number, meter number, or smartcard number', max_length=100)),
                ('variation_code', models.CharField(blank=True, max_length=100)),
                ('plan_name', models.CharField(blank=True, max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('authorization_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('token', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
