# Generated by Django 6.0.5 on 2026-07-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('success', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
