# Generated by Django 6.0.5 on 2026-07-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_checkout', '0002_alter_guesttransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesttransaction',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='guesttransaction',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guesttransaction',
            name='refund_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='guesttransaction',
            name='refund_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='guesttransaction',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guesttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('success', 'Successful'), ('failed', 'Failed'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('refund_failed', 'Refund Failed')], default='pending', max_length=20),
        ),
    ]
