# Generated by Django 6.0.5 on 2026-06-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimetransaction',
            name='network',
            field=models.CharField(choices=[('mtn', 'MTN'), ('airtel', 'Airtel'), ('glo', 'Glo'), ('9mobile', '9mobile'), ('etisalat', '9mobile / Etisalat')], max_length=20),
        ),
    ]
