# Generated by Django 6.0.5 on 2026-07-15 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_level', models.PositiveSmallIntegerField(choices=[(1, 'Registered'), (2, 'Identity Verified'), (3, 'Enhanced Verification')], default=1)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('residential_address', models.TextField(blank=True)),
                ('document_type', models.CharField(blank=True, choices=[('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('international_passport', 'International Passport'), ('voters_card', "Voter's Card")], max_length=40)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('document_front', models.ImageField(blank=True, null=True, upload_to='kyc/documents/front/%Y/%m/')),
                ('document_back', models.ImageField(blank=True, null=True, upload_to='kyc/documents/back/%Y/%m/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='kyc/selfies/%Y/%m/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
