# Generated by Django 6.0.5 on 2026-07-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='automated_verification_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='automated_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='document_authentic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='face_match_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='face_match_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='liveness_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='provider_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='verification_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
