# Generated by Django 6.0.5 on 2026-07-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycverification_automated_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='automated_verification_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='identity_match_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='verification_provider',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
