# Generated by Django 6.0.5 on 2026-08-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_kycverification_automated_verification_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='identity_verification_method',
            field=models.CharField(blank=True, choices=[('bvn', 'BVN'), ('phone_number', 'Phone Number')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='identity_verification_value',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
