# Generated by Django 6.0.5 on 2026-09-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_remove_kycverification_provider_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='identity_verification_last4',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
