# Generated by Django 6.0.5 on 2026-08-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('transaction', 'Transaction'), ('refund', 'Refund'), ('kyc', 'KYC'), ('promotion', 'Promotion'), ('security', 'Security'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
